---
services:
  rclone-webdav:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rclone-gui
    environment:
      - USER_RCLONE=adm
      - PASSWORD_RCLONE=pass
    volumes:
      - /path/to/config:/root/.config/rclone
    restart: unless-stopped
    network_mode: bridge
    hostname: rclone-gui